2016-04-29 16:15:41,741 - teradata.udaexec - INFO - Initializing UdaExec...
2016-04-29 16:15:41,741 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\TL151006\\udaexec.ini: Not Found', 'C:\\Users\\TL151006\\Desktop\\dev\\trunk\\tests\\sit_jmeter_poc\\tl151006\\test\\udaexec.ini: Not Found']
2016-04-29 16:15:41,741 - teradata.udaexec - INFO - Found run number file: "C:\Users\TL151006\Desktop\dev\trunk\tests\sit_jmeter_poc\tl151006\test\.runNumber"
2016-04-29 16:15:41,741 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-04-29 16:15:41,741 - teradata.udaexec - INFO - Removed 0 log files.
2016-04-29 16:15:41,757 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\TL151006\Desktop\dev\trunk\tests\sit_jmeter_poc\tl151006\test\PYTEST.checkpoint
2016-04-29 16:15:41,757 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-04-29 16:15:41,757 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: PYTEST
 *          Version: 1.0
 *       Run Number: 20160429161541-5
 *             Host: WUSTL151006-357
 *         Platform: Windows-7-6.1.7601-SP1
 *          OS User: tl151006
 *   Python Version: 3.5.0
 *  Python Compiler: MSC v.1900 64 bit (AMD64)
 *     Python Build: ('v3.5.0:374f501f4567', 'Sep 13 2015 02:27:37')
 *  UdaExec Version: 15.10.0.15
 *     Program Name: test_python.py
 *      Working Dir: C:\Users\TL151006\Desktop\dev\trunk\tests\sit_jmeter_poc\tl151006\test
 *          Log Dir: C:\Users\TL151006\Desktop\dev\trunk\tests\sit_jmeter_poc\tl151006\test\logs
 *         Log File: C:\Users\TL151006\Desktop\dev\trunk\tests\sit_jmeter_poc\tl151006\test\logs\PYTEST.20160429161541-5.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\TL151006\\udaexec.ini: Not Found', 'C:\\Users\\TL151006\\Desktop\\dev\\trunk\\tests\\sit_jmeter_poc\\tl151006\\test\\udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=PYTEST;Version=1.0;JobID=20160429161541-5;ClientUser=tl151006;Production=False;udaAppLogFile=C:\Users\TL151006\Desktop\dev\trunk\tests\sit_jmeter_poc\tl151006\test\logs\PYTEST.20160429161541-5.log;UtilityName=PyTd;UtilityVersion=15.10.0.15
********************************************************************************/
2016-04-29 16:15:41,772 - teradata.udaexec - INFO - Creating connection: {'password': 'XXXXXX', 'method': 'odbc', 'system': 'monopoly', 'username': 'dbc'}
2016-04-29 16:15:58,738 - teradata.udaexec - INFO - Connection successful. Duration: 16.965 seconds. Details: {'password': 'XXXXXX', 'method': 'odbc', 'system': 'monopoly', 'username': 'dbc'}
2016-04-29 16:16:02,123 - teradata.udaexec - INFO - Query Successful. Duration: 3.385 seconds, Rows: 55, Query: select TableName, TableKind from DBC.Tables where DatabaseName = 'sit_pdm'
2016-04-29 16:16:11,468 - root - INFO - ================= End: Test Success!] =================
2016-04-29 16:16:11,484 - teradata.udaexec - INFO - UdaExec exiting.
